---
version: "3.8"
# name: olw1-punkapi
services:
  app:
    build:
      context: ./vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        NODE_VERSION: '${NODE_VERSION:-18}'
        CI_COMMIT_SHA: '${CI_COMMIT_SHA}'
        CI_COMMIT_SHORT_SHA: '${CI_COMMIT_SHORT_SHA}'
        CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
        CI_COMMIT_SHORT_REF_NAME: '${CI_COMMIT_SHORT_REF_NAME}'
        CI_PROJECT_NAME: '${CI_PROJECT_NAME}'
      labels:
        - "com.${CI_PROJECT_NAME}.description=Accounting webapp"
        - "com.${CI_PROJECT_NAME}.department=Finance"
        - "com.${CI_PROJECT_NAME}.label-with-empty-value="
        - "com.${CI_PROJECT_NAME}.branch=${CI_COMMIT_REF_NAME}"
        - "com.${CI_PROJECT_NAME}.commit=${CI_COMMIT_SHA}"
        - "com.${CI_PROJECT_NAME}.commit-short=${CI_COMMIT_SHORT_SHA}"
        - "traefik.docker.network=proxy_network"
        - "traefik.enable=true"
        - "traefik.http.middlewares.${CI_PROJECT_NAME}_https.redirectscheme.scheme=https"
        - "traefik.http.routers.${CI_PROJECT_NAME}_https.entrypoints=websecure"
        - "traefik.http.routers.${CI_PROJECT_NAME}_https.rule=Host(`${CI_PROJECT_NAME}${CI_COMMIT_SHORT_REF_NAME}.manaus.am.gov.br`)"
        - "traefik.http.routers.${CI_PROJECT_NAME}_https.service=${CI_PROJECT_NAME}_http"
        - "traefik.http.routers.${CI_PROJECT_NAME}_https.tls=true"
        - "traefik.http.routers.${CI_PROJECT_NAME}_http.entrypoints=web"
        - "traefik.http.routers.${CI_PROJECT_NAME}_http.middlewares=${CI_PROJECT_NAME}_https"
        - "traefik.http.routers.${CI_PROJECT_NAME}_http.rule=Host(`${CI_PROJECT_NAME}${CI_COMMIT_SHORT_REF_NAME}.manaus.am.gov.br`)"
        - "traefik.http.routers.${CI_PROJECT_NAME}_http.service=${CI_PROJECT_NAME}_http"
        - "traefik.http.services.${CI_PROJECT_NAME}_http.loadbalancer.server.port=80"
      tags:
        - 'rodrigocabral78/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}'
        - 'rodrigocabral78/${CI_PROJECT_NAME}:latest'
        - 'sail-8.2/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}'
        - 'sail-8.2/${CI_PROJECT_NAME}:latest'
        - 'sail-8.2/app:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}'
        - 'sail-8.2/app:latest'
    image: sail-8.2/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    dns:
    - 172.17.102.2
    - 172.17.102.3
    - 8.8.4.4
    - 8.8.8.8
    - 9.9.9.9
    dns_search:
    - manaus.am.gov.br
    - google.com.br
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      CI_COMMIT_SHA: '${CI_COMMIT_SHA}'
      CI_COMMIT_SHORT_SHA: '${CI_COMMIT_SHORT_SHA}'
      CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
      - meilisearch
      - minio
      - selenium
      - mailpit
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    volumes:
      - 'sail-meilisearch:/meili_data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:7700/health'
      retries: 3
      timeout: 5s
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
    environment:
      MINIO_ROOT_USER: sail
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'sail-minio-data:/data'
      - 'sail-minio:/data/minio'
    networks:
      - sail
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s
  selenium:
    image: selenium/standalone-chrome
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - sail
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
  sail-minio-data:
    driver: local
  sail-minio:
    driver: local
